POST http://localhost:2020/api/v1/on-covid-19/json HTTP/1.1
Content-Type: application/json

{
    "region": {
    "name": "Africa",
    "avgAge": 19.7,
    "avgDailyIncomeInUSD": 4,
    "avgDailyIncomePopulation": 0.73
    },
    "periodType": "days",
    "timeToElapse": 38,
    "reportedCases": 2747,
    "population": 92931687,
    "totalHospitalBeds": 678874
}
###

get http://localhost:2020/api/v1/on-covid-19/json HTTP/1.1